# Geo-unblocking domains
netflix.com
*.netflix.com
nflximg.net
*.nflximg.net
nflxvideo.net
*.nflxvideo.net
nflxso.net
*.nflxso.net
hulu.com
*.hulu.com
huluim.com
*.huluim.com
hulu.tv
*.hulu.tv
disney.com
*.disney.com
disneyplus.com
*.disneyplus.com
bamgrid.com
*.bamgrid.com
disney.io
*.disney.io
dssott.com
*.dssott.com
amazon.com
*.amazon.com
amazonvideo.com
*.amazonvideo.com
amazontrust.com
*.amazontrust.com
primevideo.com
*.primevideo.com
hbo.com
*.hbo.com
hbogo.com
*.hbogo.com
hbomax.com
*.hbomax.com
bbc.com
*.bbc.com
bbc.co.uk
*.bbc.co.uk
bbci.co.uk
*.bbci.co.uk
itv.com
*.itv.com
itvstatic.com
*.itvstatic.com
channel4.com
*.channel4.com
c4assets.com
*.c4assets.com
espn.com
*.espn.com
espncdn.com
*.espncdn.com
twitter.com
*.twitter.com
twimg.com
*.twimg.com
facebook.com
*.facebook.com
fbcdn.net
*.fbcdn.net
instagram.com
*.instagram.com
cnn.com
*.cnn.com
bbc.co.uk
*.bbc.co.uk
reuters.com
*.reuters.com
steam.com
*.steam.com
steamcommunity.com
*.steamcommunity.com
steamstatic.com
*.steamstatic.com
spotify.com
*.spotify.com
scdn.co
*.scdn.co
pandora.com
*.pandora.com
reddit.com
*.reddit.com
redd.it
*.redd.it
youtube.com
*.youtube.com
googlevideo.com
*.googlevideo.com
ytimg.com
*.ytimg.com